[package]
name = "mba"
version = "0.1.0"
edition = "2021"

[dependencies]
rug = { version = "1", features = ["integer", "rational", "rand", "num-traits"] }
rand = "0.8"
num-traits = "0.2"
z3 = { version = "0.11", optional = true }
z3-sys = { version = "0.7", optional = true }

[features]
z3 = ["dep:z3", "dep:z3-sys"]