unstable_features = true
max_width = 80
use_small_heuristics = "Max"
condense_wildcard_suffixes = true
format_strings = true
hex_literal_case = "Lower"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
use_field_init_shorthand = true
wrap_comments = true